### ISSUE TITLE
Temporary Warp wears off too quickly

### ISSUE THREAD

**Issue by chrisbecke** [Azanor/thaumcraft-5#531] opened 2016-03-13 18:56 UTC
If the purpose of bath salts is to remove temporary warp, then they are pointless. Eating Zombie brains for example, an entire stack can be consumed, and the player will suffer, perhaps 5 or so warp events, before the temporary warp has dissapated enough that they stop, well before the other counter even counts down.

All things told, unless crafting that produces sticky warp is heavily invested in, it is actually quite difficult to maintain enough warp using temporary warp sources to suffer any of the negative consequences of warp.

**Comment by Azanor** [comment] 2016-03-14 07:16
I hate to do this, but I'm going to have to close this. There has been a big increase in suggestions or balance type posts lately and they are beginning to drown out the actual bug reports a bit. They are best posted in the MC forums instead of here - the github is for bug reports and this is not a bug report.

**Closed by Azanor** 2016-03-14 07:16 UTC

**Comment by chrisbecke** [comment] 2016-03-14 07:25
fair enough. Still, that thread has its own problems where the freeflowing discussion can drown out more serious comments on balance.

**Comment by Azanor** [comment] 2016-03-14 07:46
I think I'm going to create a suggestions area git specifically. It will make my life a lot easier while still giving people a place to post suggestions.

**Comment by Azanor** [comment] 2016-03-14 07:52
https://github.com/Azanor/thaumcraft-suggestions
