### ISSUE TITLE
Burrowing + Huge Mushrooms

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#514] opened 2016-03-09 10:10 UTC
would be nice if that'd work  :)
all mushroom blocks of a type have the same id, just different metadata
might also be a job for lumberjack seals

**Comment by Azanor** [comment] 2016-03-14 07:21
I hate to do this, but I'm going to have to close this. There has been a big increase in suggestions or balance type posts lately and they are beginning to drown out the actual bug reports a bit. They are best posted in the MC forums instead of here - the github is for bug reports and this is not a bug report.

**Closed by Azanor** 2016-03-14 07:21 UTC
