### ISSUE TITLE
Mod Sorting Issue with TC 5.1.4

### ISSUE THREAD

**Issue by oitsjustjose** [Azanor/thaumcraft-5#292] opened 2016-01-20 14:37 UTC
It's specifically 5.1.4 that causes the issue, probably related to the latest bits of integration with Botania. I've just updated Botania as well, and the issue does not occur if I revert Thaumcraft back to 5.1.3. I've tried renaming the .jar to precede Botania, but that unfortunately isn't cutting it either. Here's a photo of the FML error that shows, if that's of any assistance:

![ss 2016-01-20 at 09 33 51](https://cloud.githubusercontent.com/assets/3887324/12451744/05670386-bf59-11e5-8f82-5efcbc594bd0.png)

[And here is my latest log for you as well](http://pastebin.com/L2JLB0FK)

Let me know what else I can do!

**Comment by chitown3** [comment] 2016-01-20 14:38
Having the same issue with v5.1.4

**Comment by SirFlip** [comment] 2016-01-20 14:39
Same here

**Comment by TheWhiteWolves** [comment] 2016-01-20 15:46
Reference on our side [Issue #53](https://github.com/williewillus/Botania/issues/53)

The problem is likely due to the API for Botania wanting Thaumcraft to be loaded before it, which I don't know where its picking that up from but I guess it could be from azanor wanting it loaded first so he can do his integration, but we set botania to be loaded after Thaumcraft so its creating a loop.

@Azanor obviously I can't see how you've done the implementation but if you haven;t maybe try loading the integration stuff in the post load event? idk if that will help in this case.

**Comment by williewillus** [comment] 2016-01-20 16:00
So Botania registers its recipes in preInit, which includes several TC integration recipes. Because B is before T, FML would normally sort Botania for preInit first, leaving it unable to get any of TC's items in nonnull form to register in recipes, so Vaz put in an "after" dep for TC

I haven't really handled this situation before so idk what the best solution is. Moving the Botania recipe inits to init might have some side effects, but I'll see what I can do

**Comment by MrGraphic** [comment] 2016-01-21 00:55
Just an information for those who are stuck with this issue - remove Botania API from Thaumcraft jar file
( folder with name "Vazkii" ) and you should be able to play until prpoer fix from @Azanor .

**Comment by williewillus** [comment] 2016-01-21 01:53
@Azanor I have resolved this issue on my side, you can close this now. Thanks!

**Closed** 2016-01-21 01:56 UTC

**Comment by Azanor** [comment] 2016-01-21 06:37
Cool.
