### ISSUE TITLE
Suggestion: allow toggling of Destructive with misc-wand-toggle

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#525] opened 2016-03-10 20:30 UTC
Pressing shift all the time is annoying and can also cancel other effects you might well wan't to keep, like burrowing or refining.
Destructive is something your probably would want to toggle every now and then and creating an extra set of tools without it would just increase clutter.

**Comment by Azanor** [comment] 2016-03-14 07:20
I hate to do this, but I'm going to have to close this. There has been a big increase in suggestions or balance type posts lately and they are beginning to drown out the actual bug reports a bit. They are best posted in the MC forums instead of here - the github is for bug reports and this is not a bug report.

**Closed by Azanor** 2016-03-14 07:20 UTC

**Comment by Azanor** [comment] 2016-03-14 08:00
I created a new suggestions area for stuff like this: https://github.com/Azanor/thaumcraft-suggestions

**Comment by MalkContent** [comment] 2016-03-14 10:46
yay :) no more feeling dirty about this
