### ISSUE TITLE
Liquid Death on Dispenser?

### ISSUE THREAD

**Issue by Abadao** [Azanor/thaumcraft-5#399] opened 2016-02-13 01:47 UTC
I try put Bucket of Liquid of Death on Dispenser but its drop the Bucket of Liquid of Death instead Liquid of Death.

**Comment by chrisbecke** [comment] 2016-02-25 13:24
This is a general problem with the dispenser - being vanilla it contains hardcoded logic that supports water and lava and no other buckets. If anything, Forge should add support for this as having each mod hack the vanilla code to add their own liquid would result in a mess. As I understand the situation at least.

**Comment by chrisbecke** [comment] 2016-03-04 09:42
Also, duplicate of #367

**Closed** 2016-03-04 19:06 UTC
