### ISSUE TITLE
Any tools with the Collector effect can destroy locked blocks which placed

### ISSUE THREAD

**Issue by bunSakurAing** [Azanor/thaumcraft-5#603] opened 2016-05-22 13:23 UTC
Thaumcraft 5.2.4, the server is running with sponge
I lock a block, and then I use the wand with the Collector effect destroying the block, the block will be destroyed and then recover, it will drop as an entity and players who have been collected.
I don't know to whom I should report this problem, if this is the problem of the thaumcraft, please repair it.

**Comment by ryantheleach** [comment] 2016-05-22 17:20
Related SpongeForge issue: https://github.com/SpongePowered/SpongeForge/issues/647

**Comment by bloodmc** [comment] 2016-05-23 05:10
@bunSakurAing This has nothing to do with Thaumcraft. You need to use a protection plugin. All keys does is prevent interaction with the locked block.

@Azanor feel free to close this as it is not a bug on your end.

**Closed** 2016-05-23 06:08 UTC
